services:
  api:
    build: .
    # ports: removido intencionalmente (o Nginx assume isso)
    env_file:
      - .env
    depends_on:
      - db
    environment:
      # Agora sim, faz sentido para o seu projeto!
      DATABASE_URL: postgresql://admin_fraude:secreta@db:5432/fraudesdb

  db:
    image: postgres:15
    environment:
      # Criando um banco focado nas fraudes
      POSTGRES_DB: fraudesdb
      POSTGRES_USER: admin_fraude
      POSTGRES_PASSWORD: secreta
    volumes:
      - fraudes-pg-data:/var/lib/postgresql/data

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api

volumes:
  fraudes-dados:
  fraudes-pg-data: