name: CI API Fraude

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  verificar-sintaxe:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install autoflake black
      - run: autoflake --check --remove-all-unused-imports -r .
      - run: black --check .

  testes-smoke:
    runs-on: ubuntu-latest
    needs: verificar-sintaxe
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: |
          pip install --upgrade pip
          pip install -r requirements.txt
      - name: Rodar apenas testes essenciais (Smoke)
        run: python -m pytest tests/ -m smoke -v --tb=short

  testes-completos:
    runs-on: ubuntu-latest
    needs: testes-smoke
    # O Pulo do Gato: Este job gigante só roda em pushes diretos para a main.
    # Em Pull Requests ele será ignorado!
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: |
          pip install --upgrade pip
          pip install -r requirements.txt
      - name: Rodar TODOS os testes
        run: python -m pytest tests/ -v --tb=short